### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by SoRadGaming** [SoRadGaming/grammarly-dark#1]
List of Items to implement:
- [ ] Fix Score Colour
- [ ] Fix Loading Animation
- [ ] Add Enable/Disable Toggle
- [ ] Language Selection
- [ ] Writing Styles Settings
- [ ] Features Settings
- [ ] Subscription Page
- [ ] Style Guide
- [ ] Send Product Feedback
- [ ] What's New
- [ ] Apps UI Fix
- [ ] Product Feedback on Account Settings Page
- [ ] Upload to Chrome/Edge Stores

**Comment by SoRadGaming** [comment]
All CSS code is complete

**Comment by SoRadGaming** [comment]
Fix Highlighted Text Colour (5 Types)
